### ISSUE TITLE
crash: cannot resolve "p2m_top"

### ISSUE THREAD

**Issue by Arch-Zheng** [crash-utility/crash#102]
Hi all,

The commit 4badc6229c69f5cd9da7eb7bdf400a53ec6db01a ("Fix pvops Xen detection for kernels >= v4.20") will cause this error on arm machine:

```
crash: cannot resolve "p2m_top"
```

More detail here: https://github.com/crash-utility/crash/commit/4badc6229c69f5cd9da7eb7bdf400a53ec6db01a#commitcomment-61017469.

Thanks,
Qi

**Comment by k-hagio** [comment]
Thank you for the report.

Do you know how we can check if it's a xen dump on arm?
We can avoid the error on arm with the following, but instead we will need another way to check it for arm.
```diff
-       if (symbol_exists("xen_start_info") &&
+       if (!machine_type("ARM") &&
+           symbol_exists("xen_start_info") &&
```

**Comment by Arch-Zheng** [comment]
> Do you know how we can check if it's a xen dump on arm?

Sorry, I don't know how to check this.

> -       if (symbol_exists("xen_start_info") &&
> +       if (!machine_type("ARM") &&
> +           symbol_exists("xen_start_info") &&

BTW, not only arm, arm64 also has this problem.

**Comment by Arch-Zheng** [comment]
Hi k-hagio,

I send the fix patch([PATCH] Fix pvops Xen detection for arm machine) to the crash-utility@redhat.com, please review.

Thanks,
Qi

**Comment by AchieveZheng** [comment]
closing with https://github.com/crash-utility/crash/commit/7eba220e1a7d443cad6716dd83d4953ffd62d566.

**Comment by Arch-Zheng** [comment]
closing with https://github.com/crash-utility/crash/commit/7eba220e1a7d443cad6716dd83d4953ffd62d566.
