### ISSUE TITLE
Not able to build the crash binary

### ISSUE THREAD

**Issue by engrbansal** [crash-utility/crash#114]
Hi

today i clone the latest crash source using git clone https://github.com/crash-utility/crash.git
and then "make target=arm64" but getting below error

2022-01-21 13:56:09 (2.36 MB/s) - ‘gdb-10.2.tar.gz’ saved [40267550/40267550]

tar: Skipping to next header

gzip: stdin: invalid compressed data--crc error

gzip: stdin: invalid compressed data--length error
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:258: recipe for target 'gdb_unzip' failed
make[2]: *** [gdb_unzip] Error 2
Makefile:234: recipe for target 'gdb_merge' failed
make[1]: *** [gdb_merge] Error 2
Makefile:229: recipe for target 'all' failed
make: *** [all] Error 2

Am I missing something. Please help to resolve this.

**Comment by k-hagio** [comment]
The tar.gz file looks broken, please try again from git clone.

**Comment by engrbansal** [comment]
I tried again using git clone

step 1 : git clone https://github.com/crash-utility/crash.git
step 2 : cd crash
step 3: make target=arm64

TARGET: ARM64
 CRASH: 8.0.0++
   GDB: 10.2

--2022-01-21 15:28:50--  http://ftp.gnu.org/gnu/gdb/gdb-10.2.tar.gz
Resolving ftp.gnu.org (ftp.gnu.org)... 209.51.188.20, 2001:470:142:3::b
Connecting to ftp.gnu.org (ftp.gnu.org)|209.51.188.20|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40267550 (38M) [application/x-gzip]
Saving to: ‘gdb-10.2.tar.gz’

gdb-10.2.tar.gz                       12%[=======>                                                             ]   4.92M   241KB/s    in 20s

2022-01-21 15:29:16 (256 KB/s) - Connection closed at byte 5157949. Retrying.

--2022-01-21 15:29:17--  (try: 2)  http://ftp.gnu.org/gnu/gdb/gdb-10.2.tar.gz
Connecting to ftp.gnu.org (ftp.gnu.org)|209.51.188.20|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 40267550 (38M), 35109601 (33M) remaining [application/x-gzip]
Saving to: ‘gdb-10.2.tar.gz’

gdb-10.2.tar.gz                      100%[++++++++============================================================>]  38.40M  8.80MB/s    in 29s

2022-01-21 15:29:53 (1.14 MB/s) - ‘gdb-10.2.tar.gz’ saved [40267550/40267550]

tar: Skipping to next header

gzip: stdin: invalid compressed data--crc error

gzip: stdin: invalid compressed data--length error
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:258: recipe for target 'gdb_unzip' failed
make[2]: *** [gdb_unzip] Error 2
Makefile:234: recipe for target 'gdb_merge' failed
make[1]: *** [gdb_merge] Error 2
Makefile:229: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by k-hagio** [comment]
Is there any problem with the tar.gz file, or Makefile?
Please narrow down.. md5sum at my end:
```
$ md5sum gdb-10.2.tar.gz
7aeb896762924ae9a2ec59525088bada  gdb-10.2.tar.gz
```

**Comment by engrbansal** [comment]
could be problem with tar.gz file but not sure, crash-7.3 is working fine for me. only getting problem with gdb-10.2

$ md5sum gdb-10.2.tar.gz
f03fdde2bf0d986a9f2d7596ce7dc610  gdb-10.2.tar.gz

**Comment by engrbansal** [comment]
now it is working with some WA
i download the gdb-10.2.tar.gz from http://ftp.gnu.org/gnu/gdb/gdb-10.2.tar.gz and copy in crash folder

remove the gdb-10.2 folder
then make clean
then make target=arm64
