### ISSUE TITLE
some trouble I meet when I use the crash -utility to parse the dump of arch arm64

### ISSUE THREAD

**Issue by hzy0** [crash-utility/crash#12]
the error like this ：
crash64> extend /home/huangzaiyang/WorkSpack/crash_ext_64/gcore.so
/home/huangzaiyang/WorkSpack/crash_ext_64/gcore.so: shared object already loaded

crash64> bt
PID: 545    TASK: ffffffc0620cf000  CPU: 3   COMMAND: "ftmdaemon"
bt: WARNING: cannot determine starting stack frame for task ffffffc0620cf000

crash64> gcore 545
Failed.

can any body help me with this？

**Comment by crash-utility** [comment]
I am not the author/maintainer of the gcore extension module,
and this is not the proper location to seek answers about it.

Please post your question here on the crash utility mailing list:

  crash-utility@redhat.com

It is a moderated list, but I am the moderator, so when I see your
post, I will allow it.  Or you can subscribe to the list.

Thanks,
  Dave Anderson

----- Original Message -----
