### ISSUE TITLE
crash can't switch frame and look up the local variable of stack

### ISSUE THREAD

**Issue by goxxx** [crash-utility/crash#13]
crash can't switch frame and look up the local variable of stack like gdb
p local_var_a
p local_var_b
f 1
f 2
f 3
is there any plan support those operation?

**Comment by crash-utility** [comment]
----- Original Message -----
> crash can't switch frame and look up the local variable of stack like gdb
> p local_var_a
> p local_var_b
> f 1
> f 2
> f 3
> is there any plan support those operation?

No.  

For local variables, the best that can be done is to use "bt -f", "bt -F"
or "bt -FF", disassemble the function, and dig them out.
