### ISSUE TITLE
How to support for android15-linux6.6 gki crash tools ?

### ISSUE THREAD

**Issue by KangHoupeng** [crash-utility/crash#187]
The gki_defconfig supports CONFIG_DEBUG_INFO_COMPRESSED_ZSTD configuration, and when I build crash tools by using the command 'make zstd target=ARM64',  the gdb_session_init anoundced that 'no debugging data available'. 

`
BFD: /home/kanghoupeng/projects/crashdump/android/vmlinux: unknown type [0x13] section `.relr.dyn'
BFD: /home/kanghoupeng/projects/crashdump/android/vmlinux: unable to initialize decompress status for section .debug_aranges
"0x7ffd54714e70s": not in executable format: file format not recognized
crash: gdb_session_init 168 ...
crash: android/vmlinux: [2] no debugging data available
`

**Comment by KangHoupeng** [comment]
It's done.
`llvm-objcopy --decompress-debug-sections vmlinux `

**Comment by gnuisunix** [comment]
Dear sir,

I meet the same issue with you.

I use llvm-objcopy --decompress-debug-sections vmlinux to decompress debug sections, but appear below issue, do you know the reason of this ?

GNU gdb (GDB) 16.2

Copyright (C) 2024 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software: you are free to change and redistribute it.

There is NO WARRANTY, to the extent permitted by law.

Type "show copying" and "show warranty" for details.

This GDB was configured as "--host=x86_64-pc-linux-gnu --target=aarch64-elf-linux".

Type "show configuration" for configuration details.

Find the GDB manual and other documentation resources online at:

    <http://www.gnu.org/software/gdb/documentation/>.



For help, type "help".

Type "apropos word" to search for commands related to "word"...



crash: invalid kernel virtual address: ffffffc081235fb0  type: "kernel_config_data"

WARNING: cannot read kernel_config_data

crash: invalid kernel virtual address: ffffffc0824b4ba8  type: "possible"

WARNING: cannot read cpu_possible_map

crash: invalid kernel virtual address: ffffffc0824b4ba0  type: "present"

WARNING: cannot read cpu_present_map

crash: invalid kernel virtual address: ffffffc0824b4b98  type: "online"

WARNING: cannot read cpu_online_map

crash: invalid kernel virtual address: ffffffc0824b4bb0  type: "active"

WARNING: cannot read cpu_active_map

crash: invalid kernel virtual address: ffffffc084bd5bf8  type: "shadow_timekeeper xtime_sec"

crash: invalid kernel virtual address: ffffffc08267b4e8  type: "init_uts_ns"

WARNING: invalid linux_banner pointer: ffffffc08149e7f0

crash: vmlinux_1756 and SYS_COREDUMP do not match!


Thanks a lot !
