### ISSUE TITLE
Cannot build target ARM with Ubuntu 16.04

### ISSUE THREAD

**Issue by Evanok** [crash-utility/crash#24]
Hi.

I am able to build default target on my host (x86_64 arch) on ubuntu 16.04. But I need to build crash for ARM target.
So I run command : make target=ARM as suggested in the documentation.

Result : 

```
configure: WARNING: no enhanced curses library found; disabling TUI
checking for library containing tgetent... no
configure: error: no termcap library found
Makefile:8235: recipe for target 'configure-gdb' failed
make[3]: *** [configure-gdb] Error 1
Makefile:834: recipe for target 'all' failed
make[2]: *** [all] Error 2

crash build failed

Makefile:229: recipe for target 'gdb_merge' failed
make[1]: *** [gdb_merge] Error 1
Makefile:224: recipe for target 'all' failed
make: *** [all] Error 2
```

I check and libncurses is already installed : 

```
[arthur * (HEAD detached at 7.2.1)] sudo apt-get install libncurses5
[sudo] password for arthur: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libncurses5 is already the newest version (6.0+20160213-1ubuntu1).
```

I tried to build it with last master and last tag (7.2.1) without more success.
Do I miss something ?

Thanks,
Eva.

**Comment by crash-utility** [comment]
----- Original Message -----
> Hi.
> 
> I am able to build default target on my host (x86_64 arch) on ubuntu 16.04.
> But I need to build crash for ARM target.
> So I run command : make target=ARM as suggested in the documentation.
> 
> Result :
> 
> ```
> configure: WARNING: no enhanced curses library found; disabling TUI
> checking for library containing tgetent... no
> configure: error: no termcap library found
> Makefile:8235: recipe for target 'configure-gdb' failed
> make[3]: *** [configure-gdb] Error 1
> Makefile:834: recipe for target 'all' failed
> make[2]: *** [all] Error 2
> 
> crash build failed
> 
> Makefile:229: recipe for target 'gdb_merge' failed
> make[1]: *** [gdb_merge] Error 1
> Makefile:224: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> I check and libncurses is already installed :
> 
> ```
> [arthur * (HEAD detached at 7.2.1)] sudo apt-get install libncurses5
> [sudo] password for arthur:
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libncurses5 is already the newest version (6.0+20160213-1ubuntu1).
> ```
> 
> I tried to build it with last master and last tag (7.2.1) without more success.
> Do I miss something ?
> 
> Thanks,
> Eva.


I can't speak to the details of Ubunutu packaging, so I'll have to 
reference RPM-based host build systems.

With "make target=ARM" you are actually building a 32-bit x86
binary, and therefore it needs the 32-bit version of the ncurses
library.  On my x86_64 host, note that it has both the x86_64 
and i686 versions of the ncurses packages installed:
  
  $ rpm -qa | grep curses
  ncurses-devel-5.9-13.20130511.el7.i686    <===
  ncurses-5.9-13.20130511.el7.x86_64
  ncurses-libs-5.9-13.20130511.el7.i686     <===
  ncurses-libs-5.9-13.20130511.el7.x86_64
  ncurses-base-5.9-13.20130511.el7.noarch
  ncurses-5.9-13.20130511.el7.i686          <===
  ncurses-devel-5.9-13.20130511.el7.x86_64
  $
  
And for looking at dumpfiles, there are a few other required
packages, listed here in the crash.spec file:

  BuildRequires: ncurses-devel zlib-devel lzo-devel bison snappy-devel
  
A 32-bit version of the "bison" package doesn't seem to be required
for the build, but for the 3 potential types of compression used by 
makedumpfile for creating compressed kdumps, I have the zlib, lzo
and snappy packages installed:
  
  $ rpm -qa | grep -e ncurses -e bison -e zlib -e lzo -e snappy | grep i686
  ncurses-devel-5.9-13.20130511.el7.i686
  ncurses-libs-5.9-13.20130511.el7.i686
  snappy-devel-1.1.0-3.el7.i686
  lzo-2.06-8.el7.i686
  zlib-devel-1.2.7-17.el7.i686
  lzo-minilzo-2.06-8.el7.i686
  zlib-static-1.2.7-17.el7.i686
  ncurses-5.9-13.20130511.el7.i686
  zlib-1.2.7-17.el7.i686
  snappy-1.1.0-3.el7.i686
  lzo-devel-2.06-8.el7.i686
  $ 

The lzo and snappy libraries are only required if you build
the upstream crash sources with "make lzo" and/or "make snappy".
But you will need 32-bit zlib packages installed.

Dave

**Comment by Evanok** [comment]
Hi Dave,

Thank you for your quick answer !

After installing ncurses for 32 bits architecture no more issue !

For ubuntu : **sudo apt-get install lib32ncurses5-dev**
Then same issue for lz but same solution : **sudo apt-get install lib32z1-dev**
