### ISSUE TITLE
Please indicate target arch in extensions.html

### ISSUE THREAD

**Issue by nhed** [crash-utility/crash#29]
`fp` for example is only for `x86_64` but from this webpage it looks like arch independent

http://people.redhat.com/~anderson/extensions.html

**Comment by crash-utility** [comment]
----- Original Message -----
> `fp` for example is only for `x86_64` but from this webpage it looks like
> arch independent
> 
> http://people.redhat.com/~anderson/extensions.html

Appended "(x86_64 only)" to the fp description 

Dave
