### ISSUE TITLE
offset 0x19 does not exist

### ISSUE THREAD

**Issue by hramrach** [crash-utility/crash#41]
[  180.501732] RIP: 0033:0x7f8593edf337
[  180.501819] Code: 25 00 00 41 00 3d 00 00 41 00 74 47 64 8b 04 25 18 00 00 00 85 c0 75 6b 44 89 e2 48 89 ee bf 9c ff ff ff b8 01 01 00 00 0f 05 <48> 3d 00 f0 ff ff 0f 87 95 00 00 00 48 8b 4c 24 28 64 48 33 0c 25
[  180.502033] RSP: 002b:00007ffc9c915b80 EFLAGS: 00000246 ORIG_RAX: 0000000000000101
[  180.502179] RAX: ffffffffffffffda RBX: 000055d574b0f2d0 RCX: 00007f8593edf337
[  180.502270] RDX: 0000000000080880 RSI: 00007ffc9c917c2f RDI: 00000000ffffff9c
[  180.502361] RBP: 00007ffc9c917c2f R08: 0000000000000000 R09: 00007ffc9c9156c0
[  180.502451] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000080880
[  180.502542] R13: 00007ffc9c915c30 R14: 0000000000000014 R15: 00007ffc9c917c2f
[  180.502633] Modules linked in: vfat fat nfsv3 nfs_acl nfs lockd grace sunrpc scsi_transport_iscsi fscache af_packet br_netfilter bridge stp llc iscsi_ibft iscsi_boot_sysfs ip6t_REJECT xt_tcpudp xt_state xt_conntrack nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c ip6table_filter ip6_tables x_tables snd_seq snd_seq_device snd_pcm_oss snd_mixer_oss dmi_sysfs msr snd_hda_codec_idt snd_hda_codec_generic coretemp ledtrig_audio kvm_intel snd_hda_intel ppdev snd_hda_codec gpio_ich iTCO_wdt iTCO_vendor_support kvm snd_hda_core snd_hwdep irqbypass snd_pcm i2c_i801 mei_me snd_timer pcspkr e1000e button snd parport_pc mei parport soundcore lpc_ich mfd_core acpi_cpufreq ext4 crc16 mbcache jbd2 sd_mod firewire_ohci firewire_core serio_raw crc_itu_t ahci libahci ehci_pci uhci_hcd ehci_hcd usbcore sr_mod cdrom thermal ata_generic pata_marvell libata sg dm_multipath dm_mod scsi_dh_rdac scsi_dh_emc scsi_dh_alua scsi_mod
[  180.503460] Supported: No, Unreleased kernel
[  180.503548] CR2: 0000000000000038
[  180.503656] ---[ end trace c1d770387093adf2 ]---
[  180.503751] RIP: 0010:cdrom_release+0x19/0x1f0 [cdrom]
[  180.503842] Code: 24 02 f7 d3 83 e3 01 eb e1 0f 1f 84 00 00 00 00 00 66 66 66 66 90 41 57 41 56 41 55 41 54 41 89 f5 55 53 48 89 fb 48 83 ec 48 <4c> 8b 27 48 c7 c7 50 34 51 c0 65 48 8b 04 25 28 00 00 00 48 89 44
[  180.504059] RSP: 0018:ffffa93140abfb08 EFLAGS: 00010292
[  180.504148] RAX: 0000000000000000 RBX: 0000000000000038 RCX: 0000000000000000
[  180.504253] RDX: ffff92a8a5d80000 RSI: 00000000080000dd RDI: 0000000000000038
[  180.504344] RBP: 00000000080000dd R08: 00000000000003b9 R09: 0000000000000037
[  180.504436] R10: 0000000000000001 R11: ffffa93140abfab0 R12: ffff92a8a1c67418
[  180.504527] R13: 00000000080000dd R14: ffff92a8a1c67400 R15: 00000000fffffffa
[  180.504619] FS:  00007f85934f0dc0(0000) GS:ffff92a8a7a00000(0000) knlGS:0000000000000000
[  180.504773] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  180.504863] CR2: 0000000000000038 CR3: 0000000126ae0000 CR4: 00000000000006f0

dis cdrom_release
0xffffffffc050d7c0 <cdrom_release>:     data32 data32 data32 xchg %ax,%ax [FTRACE NOP]
0xffffffffc050d7c5 <cdrom_release+5>:   push   %r15
0xffffffffc050d7c7 <cdrom_release+7>:   push   %r14
0xffffffffc050d7c9 <cdrom_release+9>:   push   %r13
0xffffffffc050d7cb <cdrom_release+11>:  push   %r12
0xffffffffc050d7cd <cdrom_release+13>:  mov    %esi,%r13d
0xffffffffc050d7d0 <cdrom_release+16>:  push   %rbp
0xffffffffc050d7d1 <cdrom_release+17>:  push   %rbx
0xffffffffc050d7d2 <cdrom_release+18>:  mov    %rdi,%rbx
0xffffffffc050d7d5 <cdrom_release+21>:  sub    $0x48,%rsp
0xffffffffc050d7d9 <cdrom_release+25>:  mov    (%rdi),%r12
0xffffffffc050d7dc <cdrom_release+28>:  mov    $0xffffffffc0513450,%rdi
0xffffffffc050d7e3 <cdrom_release+35>:  mov    %gs:0x28,%rax
0xffffffffc050d7ec <cdrom_release+44>:  mov    %rax,0x40(%rsp)

No offset 0x19 there

**Comment by crash-utility** [comment]
----- Original Message -----
> [  180.501732] RIP: 0033:0x7f8593edf337
> [  180.501819] Code: 25 00 00 41 00 3d 00 00 41 00 74 47 64 8b 04 25 18 00 00
> 00 85 c0 75 6b 44 89 e2 48 89 ee bf 9c ff ff ff b8 01 01 00 00 0f 05 <48> 3d
> 00 f0 ff ff 0f 87 95 00 00 00 48 8b 4c 24 28 64 48 33 0c 25
> [  180.502033] RSP: 002b:00007ffc9c915b80 EFLAGS: 00000246 ORIG_RAX:
> 0000000000000101
> [  180.502179] RAX: ffffffffffffffda RBX: 000055d574b0f2d0 RCX:
> 00007f8593edf337
> [  180.502270] RDX: 0000000000080880 RSI: 00007ffc9c917c2f RDI:
> 00000000ffffff9c
> [  180.502361] RBP: 00007ffc9c917c2f R08: 0000000000000000 R09:
> 00007ffc9c9156c0
> [  180.502451] R10: 0000000000000000 R11: 0000000000000246 R12:
> 0000000000080880
> [  180.502542] R13: 00007ffc9c915c30 R14: 0000000000000014 R15:
> 00007ffc9c917c2f
> [  180.502633] Modules linked in: vfat fat nfsv3 nfs_acl nfs lockd grace
> sunrpc scsi_transport_iscsi fscache af_packet br_netfilter bridge stp llc
> iscsi_ibft iscsi_boot_sysfs ip6t_REJECT xt_tcpudp xt_state xt_conntrack
> nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c ip6table_filter
> ip6_tables x_tables snd_seq snd_seq_device snd_pcm_oss snd_mixer_oss
> dmi_sysfs msr snd_hda_codec_idt snd_hda_codec_generic coretemp ledtrig_audio
> kvm_intel snd_hda_intel ppdev snd_hda_codec gpio_ich iTCO_wdt
> iTCO_vendor_support kvm snd_hda_core snd_hwdep irqbypass snd_pcm i2c_i801
> mei_me snd_timer pcspkr e1000e button snd parport_pc mei parport soundcore
> lpc_ich mfd_core acpi_cpufreq ext4 crc16 mbcache jbd2 sd_mod firewire_ohci
> firewire_core serio_raw crc_itu_t ahci libahci ehci_pci uhci_hcd ehci_hcd
> usbcore sr_mod cdrom thermal ata_generic pata_marvell libata sg dm_multipath
> dm_mod scsi_dh_rdac scsi_dh_emc scsi_dh_alua scsi_mod
> [  180.503460] Supported: No, Unreleased kernel
> [  180.503548] CR2: 0000000000000038
> [  180.503656] ---[ end trace c1d770387093adf2 ]---
> [  180.503751] RIP: 0010:cdrom_release+0x19/0x1f0 [cdrom]
> [  180.503842] Code: 24 02 f7 d3 83 e3 01 eb e1 0f 1f 84 00 00 00 00 00 66 66
> 66 66 90 41 57 41 56 41 55 41 54 41 89 f5 55 53 48 89 fb 48 83 ec 48 <4c> 8b
> 27 48 c7 c7 50 34 51 c0 65 48 8b 04 25 28 00 00 00 48 89 44
> [  180.504059] RSP: 0018:ffffa93140abfb08 EFLAGS: 00010292
> [  180.504148] RAX: 0000000000000000 RBX: 0000000000000038 RCX:
> 0000000000000000
> [  180.504253] RDX: ffff92a8a5d80000 RSI: 00000000080000dd RDI:
> 0000000000000038
> [  180.504344] RBP: 00000000080000dd R08: 00000000000003b9 R09:
> 0000000000000037
> [  180.504436] R10: 0000000000000001 R11: ffffa93140abfab0 R12:
> ffff92a8a1c67418
> [  180.504527] R13: 00000000080000dd R14: ffff92a8a1c67400 R15:
> 00000000fffffffa
> [  180.504619] FS:  00007f85934f0dc0(0000) GS:ffff92a8a7a00000(0000)
> knlGS:0000000000000000
> [  180.504773] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
> [  180.504863] CR2: 0000000000000038 CR3: 0000000126ae0000 CR4:
> 00000000000006f0
> 
> dis cdrom_release
> 0xffffffffc050d7c0 <cdrom_release>:     data32 data32 data32 xchg %ax,%ax
> [FTRACE NOP]
> 0xffffffffc050d7c5 <cdrom_release+5>:   push   %r15
> 0xffffffffc050d7c7 <cdrom_release+7>:   push   %r14
> 0xffffffffc050d7c9 <cdrom_release+9>:   push   %r13
> 0xffffffffc050d7cb <cdrom_release+11>:  push   %r12
> 0xffffffffc050d7cd <cdrom_release+13>:  mov    %esi,%r13d
> 0xffffffffc050d7d0 <cdrom_release+16>:  push   %rbp
> 0xffffffffc050d7d1 <cdrom_release+17>:  push   %rbx
> 0xffffffffc050d7d2 <cdrom_release+18>:  mov    %rdi,%rbx
> 0xffffffffc050d7d5 <cdrom_release+21>:  sub    $0x48,%rsp
> 0xffffffffc050d7d9 <cdrom_release+25>:  mov    (%rdi),%r12
> 0xffffffffc050d7dc <cdrom_release+28>:  mov    $0xffffffffc0513450,%rdi
> 0xffffffffc050d7e3 <cdrom_release+35>:  mov    %gs:0x28,%rax
> 0xffffffffc050d7ec <cdrom_release+44>:  mov    %rax,0x40(%rsp)
> 0xffffffffc050d7f1 <cdrom_release+49>:  xor    %eax,%eax
> 0xffffffffc050d7f3 <cdrom_release+51>:  callq  0xffffffff83d0636e <printk>
> 0xffffffffc050d7f8 <cdrom_release+56>:  mov    0x40(%rbx),%ebp
> 0xffffffffc050d7fb <cdrom_release+59>:  test   %ebp,%ebp
> 0xffffffffc050d7fd <cdrom_release+61>:  jle    0xffffffffc050d805
> <cdrom_release+69>
> 0xffffffffc050d7ff <cdrom_release+63>:  sub    $0x1,%ebp
> 0xffffffffc050d802 <cdrom_release+66>:  mov    %ebp,0x40(%rbx)
> 0xffffffffc050d805 <cdrom_release+69>:  test   %ebp,%ebp
> 0xffffffffc050d807 <cdrom_release+71>:  je     0xffffffffc050d880
> <cdrom_release+192>
> 0xffffffffc050d809 <cdrom_release+73>:  testb  $0x4,0x34(%rbx)
> 0xffffffffc050d80d <cdrom_release+77>:  mov    0x8(%r12),%rax
> 0xffffffffc050d812 <cdrom_release+82>:  je     0xffffffffc050d81a
> <cdrom_release+90>
> 0xffffffffc050d814 <cdrom_release+84>:  and    $0x40,%r13d
> 0xffffffffc050d818 <cdrom_release+88>:  jne    0xffffffffc050d871
> <cdrom_release+177>
> 0xffffffffc050d81a <cdrom_release+90>:  mov    %rbx,%rdi
> 0xffffffffc050d81d <cdrom_release+93>:  callq  0xffffffff84800c80
> <__x86_indirect_thunk_rax>
> 0xffffffffc050d822 <cdrom_release+98>:  mov    0x40(%rbx),%eax
> 0xffffffffc050d825 <cdrom_release+101>: test   %eax,%eax
> 0xffffffffc050d827 <cdrom_release+103>: je     0xffffffffc050d848
> <cdrom_release+136>
> 0xffffffffc050d829 <cdrom_release+105>: mov    0x40(%rsp),%rax
> 0xffffffffc050d82e <cdrom_release+110>: xor    %gs:0x28,%rax
> 0xffffffffc050d837 <cdrom_release+119>: jne    0xffffffffc050d87b
> <cdrom_release+187>
> 0xffffffffc050d839 <cdrom_release+121>: add    $0x48,%rsp
> 0xffffffffc050d83d <cdrom_release+125>: pop    %rbx
> 0xffffffffc050d83e <cdrom_release+126>: pop    %rbp
> 0xffffffffc050d83f <cdrom_release+127>: pop    %r12
> 0xffffffffc050d841 <cdrom_release+129>: pop    %r13
> 0xffffffffc050d843 <cdrom_release+131>: pop    %r14
> 0xffffffffc050d845 <cdrom_release+133>: pop    %r15
> 0xffffffffc050d847 <cdrom_release+135>: retq
> 0xffffffffc050d848 <cdrom_release+136>: testb  $0x2,0x34(%rbx)
> 0xffffffffc050d84c <cdrom_release+140>: je     0xffffffffc050d829
> <cdrom_release+105>
> 0xffffffffc050d84e <cdrom_release+142>: mov    (%rbx),%rdx
> 0xffffffffc050d851 <cdrom_release+145>: mov    0x28(%rbx),%eax
> 0xffffffffc050d854 <cdrom_release+148>: not    %eax
> 0xffffffffc050d856 <cdrom_release+150>: and    0x68(%rdx),%eax
> 0xffffffffc050d859 <cdrom_release+153>: test   $0x2,%al
> 0xffffffffc050d85b <cdrom_release+155>: je     0xffffffffc050d829
> <cdrom_release+105>
> 0xffffffffc050d85d <cdrom_release+157>: mov    0x28(%r12),%rax
> 0xffffffffc050d862 <cdrom_release+162>: mov    $0x1,%esi
> 0xffffffffc050d867 <cdrom_release+167>: mov    %rbx,%rdi
> 0xffffffffc050d86a <cdrom_release+170>: callq  0xffffffff84800c80
> <__x86_indirect_thunk_rax>
> 0xffffffffc050d86f <cdrom_release+175>: jmp    0xffffffffc050d829
> <cdrom_release+105>
> 0xffffffffc050d871 <cdrom_release+177>: mov    %rbx,%rdi
> 0xffffffffc050d874 <cdrom_release+180>: callq  0xffffffff84800c80
> <__x86_indirect_thunk_rax>
> 0xffffffffc050d879 <cdrom_release+185>: jmp    0xffffffffc050d829
> <cdrom_release+105>
> 0xffffffffc050d87b <cdrom_release+187>: callq  0xffffffff83c99d00
> <__stack_chk_fail>
> 0xffffffffc050d880 <cdrom_release+192>: lea    0x44(%rbx),%r14
> 0xffffffffc050d884 <cdrom_release+196>: mov    $0xffffffffc0513478,%rdi
> 0xffffffffc050d88b <cdrom_release+203>: mov    %r14,%rsi

What does "dis 0xffffffffc050d88b 10" show?

> No offset 0x1f0 there
> 
>

**Comment by crash-utility** [comment]
Now I'm confused -- in your post above, you indicate:

> No offset 0x19 there

So are you interested in 0x1f0 or 0x19?  If you mean 0x19, then it is shown:

> 0xffffffffc050d7d9 <cdrom_release+25>:  mov    (%rdi),%r12

If you want the symbol offsets shown in hexadecimal, then use "dis -x ...", or
enter the "hex" alias.

**Comment by hramrach** [comment]
Why does the tool that is supposed to work with kernel default to format different from the one used in the kernel?

**Comment by crash-utility** [comment]
----- Original Message -----
> Why does the tool that is supposed to work with kernel default to format
> different from the one used in the kernel?

It has always defaulted to using gdb defaults, allowing a user to change
it on the fly or in a .crashrc file.  The default happens to show up in
all symbol+offset expressions, regardless of the crash command.
