### ISSUE TITLE
dis -s can not work in fedora 31

### ISSUE THREAD

**Issue by prettykernel** [crash-utility/crash#47]
I have installed crash using dnf in Fedora Server 31, everything works well but dis -s.

The output likes below:

$ sudo crash
crash 7.2.6-2.fc31
...
GNU gdb (GDB) 7.6
...
This GDB was configured as "x86_64-unknown-linux-gnu"...

WARNING: kernel relocated [240MB]: patching 107037 gdb minimal_symbol values

      KERNEL: /usr/lib/debug/lib/modules/5.3.7-301.fc31.x86_64/vmlinux
    DUMPFILE: /dev/crash**
        CPUS: 8
        DATE: Sat Nov 30 14:14:44 2019
      UPTIME: 00:15:34
LOAD AVERAGE: 0.37, 0.18, 0.11
       TASKS: 515
    NODENAME: z.me
     RELEASE: 5.3.7-301.fc31.x86_64
     VERSION: #1 SMP Mon Oct 21 19:18:58 UTC 2019
     MACHINE: x86_64  (2592 Mhz)
      MEMORY: 8 GB
         PID: 2525
     COMMAND: "crash"
        TASK: ffff8c23c755bf80  [THREAD_INFO: ffff8c23c755bf80]
         CPU: 2
       STATE: TASK_RUNNING (ACTIVE)

**crash> dis -s printk
FILE: (unknown)
LINE: (unknown)
dis: printk: source code is not available**

crash> dis printk
0xffffffff9014727e <printk>:    nopl   0x0(%rax,%rax,1) [FTRACE NOP]
0xffffffff90147283 <printk+5>:  push   %rbp
0xffffffff90147284 <printk+6>:  mov    %rsp,%rbp
0xffffffff90147287 <printk+9>:  sub    $0x50,%rsp
0xffffffff9014728b <printk+13>: mov    %rsi,0x28(%rsp)
0xffffffff90147290 <printk+18>: mov    %rsp,%rsi
0xffffffff90147293 <printk+21>: mov    %rdx,0x30(%rsp)
0xffffffff90147298 <printk+26>: mov    %rcx,0x38(%rsp)
0xffffffff9014729d <printk+31>: mov    %r8,0x40(%rsp)
0xffffffff901472a2 <printk+36>: mov    %r9,0x48(%rsp)
...

However, the l command in gdb works well:
$ gdb /usr/lib/debug/usr/lib/modules/5.3.7-301.fc31.x86_64/vmlinux
(gdb) l printk
2036	 * printf(3)
2037	 *
2038	 * See the vsnprintf() documentation for format string extensions over C99.
2039	 */
2040	asmlinkage __visible int printk(const char *fmt, ...)
2041	{
2042		va_list args;
2043		int r;
2044	
2045		va_start(args, fmt);

The dis -s command also can't work when I give the path to crash explicitly (like gdb above) in command line.

I also can't compile crash from source code. when I run make, the terminal shows:
cc1:all warnings being treated as errors.
Maybe there is something wrong with the function [list_source_code](https://github.com/crash-utility/crash/blob/c1ac656508ad064ef0ef222acb73621ae0bf4f00/kernel.c#L1452).

Infos below may be helpful:

$ uname -a
Linux z.me 5.3.7-301.fc31.x86_64 #1 SMP Mon Oct 21 19:18:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ gcc --version
gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)

$ gdb --version
GNU gdb (GDB) Fedora 8.3.50.20190824-25.fc31

**Comment by crash-utility** [comment]
----- Original Message -----

> I also can't compile crash from source code. when I run make, the terminal
> shows:
> cc1:all warnings being treated as errors.

That's strange -- I have no idea why that's being imposed.  AFAIK, warnings being treated as errors
should only happen if a compile line explicitly uses -Werror.  

> Maybe there is something wrong with the function
> [list_source_code](https://github.com/crash-utility/crash/blob/c1ac656508ad064ef0ef222acb73621ae0bf4f00/kernel.c#L1452).

Yes, it looks like the function is not taking KASLR into account. If you use the virtual address
from the vmlinux file, it finds the source.

crash> sym printk
ffffffff90b5c947 (T) printk /usr/src/debug/kernel-3.10.0-957.21.3.el7/linux-3.10.0-957.21.3.el7.x86_64/kernel/printk.c: 1728
crash> gdb list *0xffffffff90b5c947
crash> sys | grep KERNEL
      KERNEL: /usr/lib/debug/lib/modules/3.10.0-957.21.3.el7.x86_64/vmlinux

crash> !nm -Bn /usr/lib/debug/lib/modules/3.10.0-957.21.3.el7.x86_64/vmlinux | grep printk | grep 947
ffffffff8175c947 T printk
crash> gdb list *0xffffffff8175c947
0xffffffff8175c947 is in printk (kernel/printk.c:1728).
1723     * printf(3)
1724     *
1725     * See the vsnprintf() documentation for format string extensions over C99.
1726     */
1727    asmlinkage int printk(const char *fmt, ...)
1728    {
1729            printk_func_t vprintk_func;
1730            va_list args;
1731            int r;
1732
crash>

**Comment by crash-utility** [comment]
FWIW, I just provisioned a new installation of Fedora fc31, and crash builds normally:

$ uname -a
Linux dell-per710-01.khw2.lab.eng.bos.redhat.com 5.3.12-300.fc31.x86_64 #1 SMP Thu Nov 21 22:52:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$

**Comment by crash-utility** [comment]
You can check what a normal build looks like by clicking on any of the builds here:

  https://koji.fedoraproject.org/koji/buildinfo?buildID=1388374

In any selected build version, you can check the per-architecture build.log to compare to yours. 

 If the build were done with -Werror by default, it wouldn't stand a chance of ever building because there are dozens of compiler warnings in the gdb source code.  I do try to address any warnings in the top-level crash source files, but there's no way I will "fix" all of the gdb warnings -- which for the most part are false alarms.

**Comment by crash-utility** [comment]
Also, until I can take a look at fixing "dis -s", you might find that "dis -l" will suffice.

**Comment by crash-utility** [comment]
https://github.com/crash-utility/crash/commit/da4a22029aa55fa55200d52f98866fce48ba720e

Fix for the "dis -s" option when running against kernels that have
been configured with CONFIG_RANDOMIZE_BASE=y (KASLR).  Without the
patch, the command option indicates that the FILE and LINE numbers
are "(unknown)", and that "source code is not available".
(anderson@redhat.com)

**Comment by prettykernel** [comment]
Thank you for your time, now dis -s works well (like below):

```
$ uname -a
Linux z.me 5.3.13-300.fc31.x86_64 #1 SMP Mon Nov 25 17:25:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ grep CONFIG_RANDOMIZE_BASE /boot/config-$(uname -r)
CONFIG_RANDOMIZE_BASE=y

$ sudo dnf groupinstall -y 'Development Tools' 'C Development Tools and Libraries'

$ sudo dnf install -y ncurses-devel zlib-devel

$ git clone https://github.com/crash-utility/crash.git

$ cd crash && LANG=C sudo make | tee ~/Desktop/crash_make.log

$ sudo ./crash
crash 7.2.7++
GNU gdb (GDB) 7.6
This GDB was configured as "x86_64-unknown-linux-gnu"...
WARNING: kernel relocated [528MB]: patching 107095 gdb minimal_symbol values

      KERNEL: /usr/lib/debug/lib/modules/5.3.13-300.fc31.x86_64/vmlinux
    DUMPFILE: /dev/crash
        CPUS: 8
        DATE: Thu Dec  5 16:11:16 2019
      UPTIME: 04:25:40
LOAD AVERAGE: 0.15, 0.03, 0.04
       TASKS: 524
    NODENAME: z.me
     RELEASE: 5.3.13-300.fc31.x86_64
     VERSION: #1 SMP Mon Nov 25 17:25:25 UTC 2019
     MACHINE: x86_64  (2592 Mhz)
      MEMORY: 8 GB
         PID: 157125
     COMMAND: "crash"
        TASK: ffff986036605f40  [THREAD_INFO: ffff986036605f40]
         CPU: 5
       STATE: TASK_RUNNING (ACTIVE)

crash> dis -s schedule
FILE: kernel/sched/core.c
LINE: 3982
  3981  asmlinkage __visible void __sched schedule(void)
* 3982  {
  3983          struct task_struct *tsk = current;
  3984
  3985          sched_submit_work(tsk);
  3986          do {
  3987                  preempt_disable();
  3988                  __schedule(false);
  3989                  sched_preempt_enable_no_resched();
  3990          } while (need_resched());
  3991          sched_update_worker(tsk);
  3992  }
```


BTW, could you please add a new option to dis command so that it can display both the C and the asm code, just like the disassemble /m does in gdb:

```
(gdb) disassemble /m schedule
Dump of assembler code for function schedule:
3946	static inline void sched_submit_work(struct task_struct *tsk)

3947	{
3948		if (!tsk->state)

3949			return;
3950	
3951		/*
3952		 * If a worker went to sleep, notify and ask workqueue whether
3953		 * it wants to wake up a task to maintain concurrency.
3954		 * As this function is called inside the schedule() context,
3955		 * we disable preemption to avoid it calling schedule() again
3956		 * in the possible wakeup of a kworker.
3957		 */
3958		if (tsk->flags & PF_WQ_WORKER) {
   0xffffffff819e0879 <+25>:	testb  $0x20,0x24(%rbp)
   0xffffffff819e087d <+29>:	jne    0xffffffff819e08c9 <schedule+105>

3959			preempt_disable();

3960			wq_worker_sleeping(tsk);
   0xffffffff819e08c9 <+105>:	mov    %rbp,%rdi
   0xffffffff819e08cc <+108>:	callq  0xffffffff810ffe40 <wq_worker_sleeping>

3961			preempt_enable_no_resched();
3962		}
3963	
3964		if (tsk_is_pi_blocked(tsk))
3965			return;
3966	
3967		/*
3968		 * If we are going to sleep and we have plugged IO queued,
3969		 * make sure to submit it to avoid deadlocks.
3970		 */
3971		if (blk_needs_flush_plug(tsk))
3972			blk_schedule_flush_plug(tsk);
--Type <RET> for more, q to quit, c to continue without paging--
3973	}
3974	
3975	static void sched_update_worker(struct task_struct *tsk)

3976	{
3977		if (tsk->flags & PF_WQ_WORKER)

3978			wq_worker_running(tsk);
   0xffffffff819e08dd <+125>:	mov    %rbp,%rdi
   0xffffffff819e08e0 <+128>:	pop    %rbx
   0xffffffff819e08e1 <+129>:	pop    %rbp
   0xffffffff819e08e2 <+130>:	jmpq   0xffffffff810ffe10 <wq_worker_running>

3979	}
3980	
3981	asmlinkage __visible void __sched schedule(void)
3982	{
   0xffffffff819e0860 <+0>:	callq  0xffffffff81a019c0 <__fentry__>

3983		struct task_struct *tsk = current;
3984	
3985		sched_submit_work(tsk);
   0xffffffff819e086f <+15>:	push   %rbx
   0xffffffff819e0870 <+16>:	mov    0x10(%rbp),%rax
   0xffffffff819e0874 <+20>:	test   %rax,%rax
   0xffffffff819e0877 <+23>:	je     0xffffffff819e0889 <schedule+41>

3986		do {

3987			preempt_disable();

3988			__schedule(false);
   0xffffffff819e0892 <+50>:	xor    %edi,%edi
   0xffffffff819e0894 <+52>:	callq  0xffffffff819e01e0 <__schedule>

3989			sched_preempt_enable_no_resched();
3990		} while (need_resched());
3991		sched_update_worker(tsk);
   0xffffffff819e08a0 <+64>:	testb  $0x20,0x24(%rbp)
   0xffffffff819e08a4 <+68>:	jne    0xffffffff819e08dd <schedule+125>
   0xffffffff819e08a6 <+70>:	pop    %rbx
   0xffffffff819e08a7 <+71>:	pop    %rbp
   0xffffffff819e08a8 <+72>:	retq   

End of assembler dump.

```

**Comment by crash-utility** [comment]
> BTW, could you please add a new option to dis command so that it can display both the C and
>  the asm code, just like the disassemble /m does in gdb:

Doing both within the constraints of either crash option looks painful, so I doubt it.
Post a patch if you can get it to work.

**Comment by crash-utility** [comment]
I say that because "dis -s" is sequential with respect to line numbers, while "dis -l" is almost always
not, or the same line number appears multiple times, etc.

**Comment by Davidrjx** [comment]
dis can not work with source code lines in debian9, anyone faced with this case?
