### ISSUE TITLE
Bitmap calculation overflow in large memory physical address scenario

### ISSUE THREAD

**Issue by cjl20062529** [crash-utility/crash#51]
hi，
I used crash to analyze vmcore under arm64 architecture, and found that when crash calculates the bitmap and pfn, an integer overflow occurs, causing the crash parsing to fail.

[root@along crash]# crash vmlinux  vmcore
......
reason: variable overflow causes a logic error in crash.
crash: page excluded: kernel virtual address: ffff0000089c9100  type: "kernel_config_data"
WARNING: cannot read kernel_config_data
crash: page excluded: kernel virtual address: ffff00000911b938  type: "possible"
WARNING: cannot read cpu_possible_map
crash: page excluded: kernel virtual address: ffff00000911b8b8  type: "present"
WARNING: cannot read cpu_present_map
crash: page excluded: kernel virtual address: ffff00000911b838  type: "online"
WARNING: cannot read cpu_online_map
crash: page excluded: kernel virtual address: ffff00000911b9b8  type: "active"
WARNING: cannot read cpu_active_map
crash: page excluded: kernel virtual address: ffff0000093ec9d0  type: "shadow_timekeeper xtime_sec"
crash: page excluded: kernel virtual address: ffff000009124d2c  type: "init_uts_ns"
crash: vmlinux and vmcore do not match!

------------------------------------------------------------
/proc/iomem info:
2e69267000-2fffffffff : System RAM
......
602770ecf000-6027ffffffff : System RAM
------------------------------------------------------------
1) calculate bitmap_len overflow in function read_dump_header()
int block_size=(int)sysconf(_SC_PAGESIZE);
off_t bitmap_len;
unsigned int bitmap_blocks;
...
bitmap_len = block_size * header->bitmap_blocks;

here block_size = 4096,   header->bitmap_blocks = 0x180a00, so bitmap_len = 0x180a00000
but block_size is int type, bitmap_blocks is unsigned int type, so block_size * header->bitmap_blocks > MAX(unsigned int)
bitmap_len overflow.

2) calculate data_offset overflow in function read_dump_header()
info in makedumpfile:
info->offset_bitmap1=0x15000 info->len_bitmap=0x182000000 bit2_offset=0xc1015000

in read_dump_header():
info->len_bitmap = header->bitmap_blocks * header->block_size = 0x182000000 is greater than the range represented by integers.

The members of the following expression are all int type, but the calculation result exceeds MAX(int), 
dd->data_offset = (1 + header->sub_hdr_size + header->bitmap_blocks) * header->block_size = 0x82015000,
The correct value is 0x182015000.

3) byte overflow in function get_bit()
static inline int
get_bit(char *map, int byte, int bit)
{
        return map[byte] & (1<<bit);
}

static inline int
page_is_ram(unsigned long nr)
{
        return get_bit(dd->bitmap, nr >> 3, nr & 7);
}
if nr=0x6027fff4f, 0x6027fff4f >> 3 =>  ‭0xC04FFFE9‬ > MAX(int),
so byte parameter overflow when call get_bit.

The following is my patch, please review. Thanks.

```
Signed-off-by: Jialong Chen <chenjialong@huawei.com>
---
 diskdump.c | 6 ++--
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/diskdump.c b/diskdump.c
index c3e343b..1a2a5ce 100644
--- a/diskdump.c
+++ b/diskdump.c
@@ -233,7 +233,7 @@ clean_diskdump_data(void)
 }

 static inline int
-get_bit(char *map, int byte, int bit)
+get_bit(char *map, unsigned long byte, int bit)
 {
        return map[byte] & (1<<bit);
 }
@@ -674,7 +674,7 @@ restart:
                dd->max_mapnr = header->max_mapnr;

        /* read memory bitmap */
-       bitmap_len = block_size * header->bitmap_blocks;
+       bitmap_len = (off_t)block_size * header->bitmap_blocks;
        dd->bitmap_len = bitmap_len;

        offset = (off_t)block_size * (1 + header->sub_hdr_size);
@@ -724,7 +724,7 @@ restart:
                memcpy(dd->dumpable_bitmap, dd->bitmap, bitmap_len);

        dd->data_offset
-               = (1 + header->sub_hdr_size + header->bitmap_blocks)
+               = (1UL + header->sub_hdr_size + header->bitmap_blocks)
                * header->block_size;

        dd->header = header;

```

**Comment by crash-utility** [comment]
Hello Jialong,

Please post your patch on the crash-utility mailing list by sending it to:

  crash-utility@redhat.com

The patch needs to be viewed by a larger audience.  The mailing list is moderated,
so I have sent an invite for you to subscribe.  If you prefer not to subscribe, 
I will accept your email for display.

Thanks,
  Dave


----- Original Message -----

**Comment by cjl20062529** [comment]
> Hello Jialong, Please post your patch on the crash-utility mailing list by sending it to: crash-utility@redhat.com The patch needs to be viewed by a larger audience. The mailing list is moderated, so I have sent an invite for you to subscribe. If you prefer not to subscribe, I will accept your email for display. Thanks, Dave
> […](#)
> ----- Original Message -----
> hi， I used crash to analyze vmcore under arm64 architecture, and found that when crash calculates the bitmap and pfn, an integer overflow occurs, causing the crash parsing to fail. ***@***.*** crash]# crash vmlinux vmcore ...... reason: variable overflow causes a logic error in crash. crash: page excluded: kernel virtual address: ffff0000089c9100 type: "kernel_config_data" WARNING: cannot read kernel_config_data crash: page excluded: kernel virtual address: ffff00000911b938 type: "possible" WARNING: cannot read cpu_possible_map crash: page excluded: kernel virtual address: ffff00000911b8b8 type: "present" WARNING: cannot read cpu_present_map crash: page excluded: kernel virtual address: ffff00000911b838 type: "online" WARNING: cannot read cpu_online_map crash: page excluded: kernel virtual address: ffff00000911b9b8 type: "active" WARNING: cannot read cpu_active_map crash: page excluded: kernel virtual address: ffff0000093ec9d0 type: "shadow_timekeeper xtime_sec" crash: page excluded: kernel virtual address: ffff000009124d2c type: "init_uts_ns" crash: vmlinux and vmcore do not match! ------------------------------------------------------------ /proc/iomem info: 2e69267000-2fffffffff : System RAM ...... 602770ecf000-6027ffffffff : System RAM ------------------------------------------------------------ 1) calculate bitmap_len overflow in function read_dump_header() int block_size=(int)sysconf(_SC_PAGESIZE); off_t bitmap_len; unsigned int bitmap_blocks; ... bitmap_len = block_size * header->bitmap_blocks; here block_size = 4096, header->bitmap_blocks = 0x180a00, so bitmap_len = 0x180a00000 but block_size is int type, bitmap_blocks is unsigned int type, so block_size * header->bitmap_blocks > MAX(unsigned int) bitmap_len overflow. 2)calculate data_offset overflow in function read_dump_header() info in makedumpfile: info->offset_bitmap1=0x15000 info->len_bitmap=0x182000000 bit2_offset=0xc1015000 in read_dump_header(): info->len_bitmap = header->bitmap_blocks * header->block_size = 0x182000000 is greater than the range represented by integers. The members of the following expression are all int type, but the calculation result exceeds MAX(int), dd->data_offset = (1 + header->sub_hdr_size + header->bitmap_blocks) * header->block_size = 0x82015000, The correct value is 0x182015000. 3) byte overfl in function get_bit() static inline int get_bit(char *map, int byte, int bit) { return map[byte] & (1<<bit); } static inline int page_is_ram(unsigned long nr) { return get_bit(dd->bitmap, nr >> 3, nr & 7); } if nr=0x6027fff4f, 0x6027fff4f >> 3 => ‭0xC04FFFE9‬ > MAX(int), so byte parameter overflow when call ***@***.*** The following is my patch, please review. Thanks. Signed-off-by: Jialong Chen ***@***.***> --- diskdump.c | 4 ++-- 1 file changed, 2 insertions(+), 2 deletions(-) diff --git a/diskdump.c b/diskdump.c index c3e343b..1a2a5ce 100644 --- a/diskdump.c +++ b/diskdump.c @@ -233,7 +233,7 @@ clean_diskdump_data(void) } static inline int -get_bit(char *map, int byte, int bit) +get_bit(char *map, unsigned long byte, int bit) { return map[byte] & (1<<bit); } @@ -674,7 +674,7 @@ restart: dd->max_mapnr = header->max_mapnr; /* read memory bitmap */ - bitmap_len = block_size * header->bitmap_blocks; + bitmap_len = (off_t)block_size * header->bitmap_blocks; dd->bitmap_len = bitmap_len; offset = (off_t)block_size * (1 + header->sub_hdr_size); @@ -724,7 +724,7 @@ restart: memcpy(dd->dumpable_bitmap, dd->bitmap, bitmap_len); dd->data_offset - = (1 + header->sub_hdr_size + header->bitmap_blocks) + = (1UL + header->sub_hdr_size + header->bitmap_blocks) * header->block_size; dd->header = header; -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #51


I have sent the patch to crash-utility@redhat.com by email, please help review the patch。
 Thanks.

**Comment by crash-utility** [comment]
----- Original Message -----
> ...
> I have sent the patch to crash-utility@redhat.com by email, please help
> review the patch。
>  Thanks.

OK thanks -- I have set up the mailing list so that any future emails from your
email address will be accepted automatically.

The patch looks good to me.  However, I do want it to be viewed by the makedumpfile
maintainer, given that the code that you have patched was originally written
by the makedumpfile authors.

Dave

**Comment by cjl20062529** [comment]
This code is indeed related to the makedumpfile software. I have modified the makedumpfile and verified it. I am also planning to send a patch to the makedumpfile community.

> ----- Original Message -----
> ... I have sent the patch to ***@***.*** by email, please help review the patch。 Thanks.
> OK thanks -- I have set up the mailing list so that any future emails from your email address will be accepted automatically. The patch looks good to me. However, I do want it to be viewed by the makedumpfile maintainer, given that the code that you have patched was originally written by the makedumpfile authors. Dave


This code is indeed related to the makedumpfile software. I have modified the makedumpfile and verified it. I am also planning to send a patch to the makedumpfile community.

**Comment by crash-utility** [comment]
Patches to makedumpfile are posted to the kexec mailing list:
 
  http://lists.infradead.org/mailman/listinfo/kexec

Please also cc: the makedumpfile maintainer, Kazuhito Hagio:
 
 k-hagio-ab@nec.com

**Comment by k-hagio** [comment]
> The patch looks good to me. However, I do want it to be viewed by the makedumpfile maintainer, given that the code that you have patched was originally written by the makedumpfile authors.

Looks good to me, too. Thanks.

**Comment by cjl20062529** [comment]
Thanks @k-hagio @crash-utility  for the guidance.
