### ISSUE TITLE
PPC64 big endian

### ISSUE THREAD

**Issue by rududoo** [crash-utility/crash#55]
Is there any support for PPC64 big endian target?

Thank you.

**Comment by k-hagio** [comment]
Yes, it's supported.  Any problems?

**Comment by rududoo** [comment]
How should I compile it for ppc64 (not ppc64le)?
The sources are on an x86-64  machine, while the target will be a ppc64 machine.

**Comment by bhupesh-sharma** [comment]
Hi,

On Mon, Jun 29, 2020 at 9:27 PM rududoo <notifications@github.com> wrote:
>
> How should I compile it for ppc64 (not ppc64le)?
> The sources are on an x86-64 machine, while the target will be a ppc64 machine.

I normally compile the ppc64-be crash utility on the ppc64-be target
like freescale boards using native gcc toolchains.
I haven't tried a cross-compilation on a x86_64 host, but I am not
sure if that would be an issue.

I think the following notes from Dave A. should help you with the same:
<https://www.redhat.com/archives/crash-utility/2012-April/msg00044.html>

I will try cross-compiling the same on a x86_64 host, but in the
meanwhile it would help further if you can share the exact compilation
issues you are facing.

Thanks,
Bhupesh

**Comment by k-hagio** [comment]
> How should I compile it for ppc64 (not ppc64le)?
> The sources are on an x86-64 machine, while the target will be a ppc64 machine.
> My intention is to analyze a vmcore from the ppc64 machine.

Ah, you want to analyze a ppc64-be vmcore on an x86_64 machine, right?
As far as I read [1] and the crash sources, that is not supported.

[1] https://github.com/crash-utility/crash/blob/master/README#L100

(To suppport it, I think the endian of all memory data read needs to be converted in crash at least.. though I'm not sure if that is enough.)

**Comment by rududoo** [comment]
Hi guys,

Thanks for the answers.
I have tried to build on the x86 machine but although I set the environment for the cross-toolchain the compilation somehow didn't take the correct sysroot and it stopped because it couldn't find  a library in /lib64/ although it shouldn't have searched in that path.

I decided then to move to the target so I copied the source tree there...cleaned the gdb folder ....rebuilt everything then rebuilt the crash. Finally I obtained a working binary  on the target.

**Comment by bhupesh-sharma** [comment]
Hello,

On Thu, Jul 2, 2020 at 1:53 AM rududoo <notifications@github.com> wrote:

> Hi guys,
>
> Thanks for the answers.
> I have tried to build on the x86 machine but although I set the
> environment for the cross-toolchain the compilation somehow didn't take the
> correct sysroot and it stopped because it couldn't find a library in
> /lib64/ although it shouldn't have searched in that path.
>
> I decided then to move to the target so I copied the source tree
> there...cleaned the gdb folder ....rebuilt everything then rebuilt the
> crash. Finally I obtained a working binary on the target.
>

Glad to know that you were able to compile the crash-utility on the
ppc64-be target directly.

Note that you will need to analyze the vmcore file via the crash-utility on
the ppc64-be target directly as well, as a x86_64 host cannot be used to
analyze the same. Kazu already noted the reason behind the same in another
reply (as the endianness on the target and host differ).

Hope this helps.

Thanks,
Bhupesh

**Comment by rududoo** [comment]
i
