### ISSUE TITLE
crash-utils should explicitly append a timezone to its DATE.

### ISSUE THREAD

**Issue by wenjianhn** [crash-utility/crash#62]
crash 7.2.8

Currently it's not easy to distinguish which timezone the output of DATE uses.

Actual:
```
crash> sys |grep -i date
        DATE: Thu Jul  2 16:54:08 2020
```
Expected:
`Thu Jul  2 16:54:08 UTC 2020`

Same format of the `date` command.

And maybe it would be nice if it uses /etc/localtime of the crashed server instead of the server used to analyze the vmcore.
Right now we can do so by using the TZ environment variable:
`TZ=/usr/share/zoneinfo/America/Danmarkshavn crash vmlinux vmcore`

**Comment by wenjianhn** [comment]
Maybe we could make kdump store its own TZ environment variable or /etc/localtime to an ELF note of the core file.
Then crash-utils extracts the timezone from it.

**Comment by k-hagio** [comment]
Good suggestion.  I think that showing the timezone of running crash would be good enough.
How about something like this?
```
--- a/kernel.c
+++ b/kernel.c
@@ -5545,8 +5545,8 @@ display_sys_stats(void)
 
 	if (ACTIVE())
 		get_xtime(&kt->date);
-        fprintf(fp, "        DATE: %s\n", 
-		strip_linefeeds(ctime(&kt->date.tv_sec))); 
+        strftime(buf, sizeof(buf), "%a %b %d %T %Z %Y", localtime(&kt->date.tv_sec));
+        fprintf(fp, "        DATE: %s\n", buf);
         fprintf(fp, "      UPTIME: %s\n", get_uptime(buf, NULL)); 
         fprintf(fp, "LOAD AVERAGE: %s\n", get_loadavg(buf)); 
 	fprintf(fp, "       TASKS: %ld\n", RUNNING_TASKS());
```

**Comment by wenjianhn** [comment]
I applied the above patch and got the timezone info:

```
crash> sys |grep -i date
        DATE: Thu Jul 02 16:54:08 CST 2020
```

Thanks.

**Comment by bhupesh-sharma** [comment]
Hi Kazu,

On Tue, Aug 18, 2020 at 2:01 PM Kazuhito Hagio <notifications@github.com>
wrote:

> Good suggestion. I think that showing the timezone of running crash would
> be good enough.
> How about something like this?
>
> --- a/kernel.c
> +++ b/kernel.c
> @@ -5545,8 +5545,8 @@ display_sys_stats(void)
>
>  	if (ACTIVE())
>  		get_xtime(&kt->date);
> -        fprintf(fp, "        DATE: %s\n",
> -		strip_linefeeds(ctime(&kt->date.tv_sec)));
> +        strftime(buf, sizeof(buf), "%a %b %d %T %Z %Y", localtime(&kt->date.tv_sec));
> +        fprintf(fp, "        DATE: %s\n", buf);
>          fprintf(fp, "      UPTIME: %s\n", get_uptime(buf, NULL));
>          fprintf(fp, "LOAD AVERAGE: %s\n", get_loadavg(buf));
>  	fprintf(fp, "       TASKS: %ld\n", RUNNING_TASKS());
>
> —
>

This seems like a good fix. I have tested the same, so:
Tested-and-Acked-by: Bhupesh Sharma <bhsharma@redhat.com>

Thanks,
Bhupesh

**Comment by k-hagio** [comment]
Thanks, but I found that there are several `ctime()` in the crash source code, I think it would be better to replace some of them with the `strftime()`.  so I will introduce a new function to replace the `ctime()` with it, and post a patch to the mailing list.

@wenjianhn could I put your `Suggested-by:` tag on the patch?  Is `Suggested-by: Jacob Wen <wenjianhn@gmail.com>` ok?

**Comment by wenjianhn** [comment]
@k-hagio Yes. Please use my company's email addr.
Thanks.

Suggested-by: Jacob Wen <jian.w.wen@oracle.com>

**Comment by k-hagio** [comment]
Thanks, posted a patch [1] with the tag.  @bhupesh-sharma could you review it again?

[1] https://www.redhat.com/archives/crash-utility/2020-August/msg00054.html
