### ISSUE TITLE
cannot determine length of symbol: log_end

### ISSUE THREAD

**Issue by threeearcat** [crash-utility/crash#67]
Hi, I have a problem with the latest kernel and the latest crash.
My kernel is built on the commit `f9893351acaecf0a414baf9942b48d5bb5c688c6`,
and the crash is built on the commit `17e6a44b406cbf07ab8d82cbaf4c52404ec46ba7`.

When I ran the crash `crash ./vmlinux ./vmcore`, I got the following error message.
`crash: cannot determine length of symbol: log_end.`.
The vmcore file is generated with QEMU and its arch is x86_64.

It worked fine with a kernel commit generated about a month ago (I don't remember the exact commit),
so I suspect recent changes of the linux kernel somehow breaks the crash.

I want to do my own research on it, but I don't know where to start.
It seems a similar problem was fixed in the old crash version 6.0.8.
Do you have any advice to mitigate this problem?

**Comment by threeearcat** [comment]
I suspect that the printk rework which introduced the lockless ringbuffer is not compatible with Crash.
The printk rework is merged into the linus branch in the commit `d594d8f411d4`.
Crash works fine for me before the series of commits (0d6f55403a47^..0463d04ea03a).
I'm not sure these commits are the cause of the problem though.

**Comment by k-hagio** [comment]
Thanks for the report.
Yes, there is an RFC patch for the new ringbuffer [1], but apparently there has been long discussion until the kernel patches were merged, it might need some fixes.
[1] https://www.redhat.com/archives/crash-utility/2020-April/msg00080.html

**Comment by threeearcat** [comment]
Then I will calmly wait for the upcoming patch.
Before it shows up, I can revert commits for the lockless ringbuffer, which is totally fine for me.
Thanks you!

**Comment by k-hagio** [comment]
Just FYI, `crash -s` can start its session even on 5.10-rc1 kernel
without the error `crash: cannot determine length of symbol: log_end`.
Of course, currently the `log` command doesn't work, though.
