### ISSUE TITLE
crash crash-7.2.9  Fails to read Xen vmcore  generated on Dom0  from Linux 4.14.205.

### ISSUE THREAD

**Issue by jpdonnell** [crash-utility/crash#78]
A vmcore core generated with makedumpfile -d1 ( or -d0 ") can not be processed.
It fails with :

crash: seek error: physical address: 83640e000  type: "pud page"

Adding debug to crash  ( -d 8 ) shows this sequence of messages  : 

<readmem: 83640e000, PHYSADDR, "pud page", 4096, (FOE), 2a74f20>
<read_diskdump: addr: 83640e000 paddr: 83640e000 cnt: 4096>
xen_kdump_p2m: paddr/pfn: 83640e000/83640e: read mfn_frame: 1049d27000
<readmem: 1049d27000, PHYSADDR, "xen_kdump_p2m mfn frame", 4096, (ROE), 3a06e80>
<read_diskdump: addr: 1049d27000 paddr: 1049d27000 cnt: 4096>
read_diskdump: xen_kdump_p2m(1049d27000): 1049d27000
read_diskdump: paddr/pfn: 1049d27000/1049d27 -> cache physical page: 1049d27000
xen_kdump_p2m(83640e000): mfn_idx: 16818 frame_idx: 14 mfn_frame: 1049d27 mfn: ffffffffffffffff => fffffffffffff000
read_diskdump: xen_kdump_p2m(83640e000): fffffffffffff000
read_diskdump: SEEK_ERROR: paddr/pfn: fffffffffffff000/fffffffffffff max_mapnr: 1080000
crash: seek error: physical address: 83640e000  type: "pud page"

It appears to me 

 mfn: ffffffffffffffff => fffffffffffff000

Is not valid.

I am not certain if this is a kernel issue or crash issue. 

--

makefiledump messages:

makedumpfile -X -d 0 --message-level 31 -D --work-dir=/tmp /proc/vmcore /kdumproot/home//crash/127.0.0.1-2021-04-06-12:45:10/vmcore-incomplete
sadump: does not have partition header
sadump: read dump device as unknown format
sadump: unknown format
               phys_start         phys_end       virt_start         virt_end
LOAD[ 0]                0            9b000 ffff880000000000 ffff88000009b000
LOAD[ 1]           100000         57000000 ffff880000100000 ffff880057000000
LOAD[ 2]         77000000         77928000 ffff880077000000 ffff880077928000
LOAD[ 3]         7bd4d000         7bd58000 ffff88007bd4d000 ffff88007bd58000
LOAD[ 4]         7bd59000         7bd5c000 ffff88007bd59000 ffff88007bd5c000
LOAD[ 5]         7bd5d000         7bd5e000 ffff88007bd5d000 ffff88007bd5e000
LOAD[ 6]         7bde4000         7c000000 ffff88007bde4000 ffff88007c000000
LOAD[ 7]        100000000       1080000000 ffff880100000000 ffff881080000000
Xen kdump
page_size    : 4096

SYMBOL(dom_xen): ffff82d080740350
SYMBOL(dom_io): ffff82d080740348
SYMBOL(domain_list): ffff82d0805413a8
SYMBOL(xen_heap_start): 0
SYMBOL(frame_table): ffff82d08038b018
SYMBOL(alloc_bitmap): 0
SYMBOL(max_page): ffff82d080740338
SYMBOL(pgd_l2): 0
SYMBOL(pgd_l3): 0
SYMBOL(pgd_l4): ffff82d0803c0000
SYMBOL(xenheap_phys_end): 0
SYMBOL(xen_pstart): 0
SYMBOL(frametable_pg_dir): 0
SIZE(page_info): 32
OFFSET(page_info.count_info): 8
OFFSET(page_info._domain): 24
SIZE(domain): 3712
OFFSET(domain.domain_id): 0
OFFSET(domain.next_in_list): 112

xen_major_version: 4
xen_minor_version: 4
xen_phys_start: 77000000
frame_table_vaddr: ffff82e000000000
xen_heap_start: 0
xen_heap_end:0
alloc_bitmap: 0
max_page: 0
num_domain: 3
 0: 839b07: ffff830839b07000
 32754: 839d99: ffff830839d99000
 32753: 83ff89: ffff83083ff89000

max_mapnr    : 1080000

max_mapnr    : 1080000
                       mem_map        pfn_start          pfn_end
mem_map[   0]                0                0                0
mmap() is available on the kernel.
Checking for memory holes                         : [100.0 %] |    [Checking for memory holes  ] : 0.098263 seconds
Copying data                                      : [100.0 %] -          output line

----

Thank you.

**Comment by jpdonnell** [comment]
Closer inspection of xen_kdump_p2m()

xen_kdump_p2m (pseudo=0x83640e000) at xen_dom0.c:254

Line 254

 res = readmem((physaddr_t)PTOB(mfn_frame), PHYSADDR,
(gdb) p *xkd
$2 = {
  flags = 0x5,
  cr3 = 0x0,
  p2m_mfn = 0x1049911,
  page = 0x2007dc0 "",
  last_mfn_read = 0x1049d0e,
  last_pmd_read = 0xffffffffffffffff,
  cache_hits = 0xca0,
  accesses = 0xce2,
  p2m_frames = 0x40000,
  p2m_mfn_frame_list = 0x248e8a0,
  xen_phys_start = 0x77000000,
  xen_major_version = 0x4,
  xen_minor_version = 0x4
}
(gdb) p mfn_frame
$3 = 0x1049d27
(gdb) x/20g xkd->page
0x2007dc0: 0x0000000000836400 0x0000000000836401
0x2007dd0: 0x0000000000836402 0x0000000000836403
0x2007de0: 0x0000000000836404 0x0000000000836405
0x2007df0: 0x0000000000836406 0x0000000000836407
0x2007e00: 0x0000000000836408 0x0000000000836409
0x2007e10: 0x000000000083640a 0x000000000083640b
0x2007e20: 0x000000000083640c 0x000000000083640d


The previous read of  xkd->page   shows  mfn 

The failing read returns 0xfff

(gdb) x/20g xkd->page
0x2007dc0: 0xffffffffffffffff 0xffffffffffffffff
0x2007dd0: 0xffffffffffffffff 0xffffffffffffffff
0x2007de0: 0xffffffffffffffff 0xffffffffffffffff


Which is used to calculate the mfn

263 xkd->last_mfn_read = mfn_frame;
264
265 mfnptr = ((ulong *)(xkd->page)) + frame_idx;
266 paddr = (physaddr_t)PTOB((ulonglong)(*mfnptr));
267 paddr |= PAGEOFFSET(pseudo);
268

(gdb) p frame_idx
$6 = 0xe

**Comment by jpdonnell** [comment]
Tracked down the issue in crash:

--- a/kernel.c
+++ b/kernel.c
@@ -172,8 +172,8 @@ kernel_init()
        if (PVOPS() && symbol_exists("pv_init_ops") &&
            readmem(symbol_value("pv_init_ops"), KVADDR, &pv_init_ops,
            sizeof(void *), "pv_init_ops", RETURN_ON_ERROR) &&
-           (p1 = value_symbol(pv_init_ops)) &&
-           STREQ(p1, "xen_patch")) {
+           (p1 = value_symbol(pv_init_ops))) {
+           //  -->>>  BROKE  STREQ(p1, "xen_patch")) {
                kt->flags |= ARCH_XEN | ARCH_PVOPS_XEN;


Removing the test for xen_patch fixes the issue.  

--

 Kernel side: 


"xen_patch" as removed by : 

commit edcb5cf84f05e5d2e2af25422a72ccde359fcca9
Author: Juergen Gross <jgross@suse.com>
Date:   Wed Aug 16 19:31:56 2017 +0200    x86/paravirt/xen: Remove xen_patch()    Xen's paravirt patch function xen_patch() does some special casing for
    irq_ops functions to apply relocations when those functions can be
    patched inline instead of calls.

-       pv_init_ops = xen_init_ops;
+       pv_init_ops.patch = paravirt_patch_default;


In these kernels  : 


 git branch --contains edcb5cf84f05e5d2e2af25422a72ccde359fcca
  4.14.71
  4.18.15-1900.1.8.TopeTree
  4.20-rc1
  b4.14.71
  b4.14.80
  b4.14.90
  b4.14.y
  b4.16.18
  b4.18.20
  b4.20.14
  b5.0-rc6
  b5.2-rc2
  b5.4-rc1
  b_linux-4.18.y
  b_v5.4.100
  linux-4.14.y
  linux-4.18.y
  linux-4.19.y
  linux-5.0.y

**Comment by jpdonnell** [comment]
This fixes crash to work with old/new kernels:




++           ((p1 = value_symbol(pv_init_ops)) &&
++                (STREQ(p1, "xen_patch") || STREQ(p1, "paravirt_patch_default")))) {

**Comment by k-hagio** [comment]
Thank you for tracking down the issue.
Is it possible for you to send the patch to the crash-utility mailing list [1]?

[1] https://listman.redhat.com/mailman/listinfo/crash-utility

**Comment by jpdonnell** [comment]
Hi. 


I am planning on doing a "pull request " .. Is that ok ?

You simply need to add an additional check the value of "p1" . .

Thank you,
John.

**Comment by k-hagio** [comment]
We currently accept only patches sent to the list because there are much more watchers there.
I would like you to do so if you don't mind, but the fix looks simple, a pull request also would be fine in this case.
Thanks.

**Comment by jpdonnell** [comment]
Hi 
 
I am kind of rusty of git-hub pull requests:


https://github.com/crash-utility/crash/pull/79

You just need the kernel.c.  change 

Thank you,.

Johnn
