### ISSUE TITLE
gdb_proc_service.h:162:9: error: unknown type name 'gdb_fpregset_t'

### ISSUE THREAD

**Issue by DengkeDu** [crash-utility/crash#8]
Hi all, when I make crash, the following appear:

> | In file included from amd64-linux-nat.c:61:0:
> | gdb_proc_service.h:162:9: error: unknown type name 'gdb_fpregset_t'
> |typedef gdb_fpregset_t gdb_prfpregset_t;
> |          ^~~~~~~~~~~~~~
> | make[4]: *** [amd64-linux-nat.o] Error 1
> | make[4]: *** Waiting for unfinished jobs....
> | make[4]: *** [linux-thread-db.o] Error 1
> | In file included from proc-service.c:28:0:
> | gdb_proc_service.h:162:9: error: unknown type name 'gdb_fpregset_t'
> |  typedef gdb_fpregset_t gdb_prfpregset_t;
> |          ^~~~~~~~~~~~~~

**Comment by DengkeDu** [comment]
The gdb_fpregset_t comes from gregset.h:
    `typedef GDB_FPREGSET_T gdb_fpregset_t;`
But it should report unknow type name ''GDB_FPREGSET_T, why gdb_prfpregset_t?

**Comment by crash-utility** [comment]
----- Original Message -----
> Hi all, when I make crash, the following appear:
> | In file included from amd64-linux-nat.c:61:0:
> | gdb_proc_service.h:162:9: error: unknown type name 'gdb_fpregset_t'
> |  typedef gdb_fpregset_t gdb_prfpregset_t;
> |          ^~~~~~~~~~~~~~
> | make[4]: *** [amd64-linux-nat.o] Error 1
> | make[4]: *** Waiting for unfinished jobs....
> | make[4]: *** [linux-thread-db.o] Error 1
> | In file included from proc-service.c:28:0:
> | gdb_proc_service.h:162:9: error: unknown type name 'gdb_fpregset_t'
> |  typedef gdb_fpregset_t gdb_prfpregset_t;
> |          ^~~~~~~~~~~~~~

I have never seen this error before.  It would seem to have something to
do with the glibc installed on your build host:

    155 /* Fix-up some broken systems.  */
    156 
    157 /* Unfortunately glibc 2.1.3 was released with a broken prfpregset_t
    158    type.  We let configure check for this lossage, and make
    159    appropriate typedefs here.  */
    160 
    161 #ifdef PRFPREGSET_T_BROKEN
    162 typedef gdb_fpregset_t gdb_prfpregset_t;
    163 #else
    164 typedef prfpregset_t gdb_prfpregset_t;
    165 #endif
    166 

----- Original Message -----
> The gdb_fpregset_t comes from gregset.h:
> typedef GDB_FPREGSET_T gdb_fpregset_t;
> But it should report unknow type name ''GDB_FPREGSET_T, why gdb_prfpregset_t?

I'm not sure what the error message should show.

Dave

**Comment by DengkeDu** [comment]
I modify the file: `gdb-7.6/gdb/gdb_proc_service.h`, let the `#include "gregset.h"` after `#include <sys/types.h>`, not in the `#ifdef HAVE_PROC_SERVICE_H ... #endif`
This change fix the build error.
