### ISSUE TITLE
crash: seek error: physical address: 46d01a000  type: "pud page" 

### ISSUE THREAD

**Issue by anlancs** [crash-utility/crash#81]
Hi I'm using debian10 with upgraded kernel 5.4.
What's wrong? I'm puzzled for a few days! 
More thanks!

crash 7.2.5
Copyright (C) 2002-2019  Red Hat, Inc.
Copyright (C) 2004, 2005, 2006, 2010  IBM Corporation
Copyright (C) 1999-2006  Hewlett-Packard Co
Copyright (C) 2005, 2006, 2011, 2012  Fujitsu Limited
Copyright (C) 2006, 2007  VA Linux Systems Japan K.K.
Copyright (C) 2005, 2011  NEC Corporation
Copyright (C) 1999, 2002, 2007  Silicon Graphics, Inc.
Copyright (C) 1999, 2000, 2001, 2002  Mission Critical Linux, Inc.
This program is free software, covered by the GNU General Public License,
and you are welcome to change it and/or distribute copies of it under
certain conditions.  Enter "help copying" to see the conditions.
This program has absolutely no warranty.  Enter "help warranty" for details.
 
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu"...

WARNING: could not find MAGIC_START!
crash: seek error: physical address: 46d01a000  type: "pud page" <-----------

More details:
<readmem: ffff88846dc7b300, KVADDR, "fill_task_struct", 3264, (ROE|Q), 55795dbc9ee0>                                                                                                                       
<read_proc_kcore: addr: ffff88846dc7b300 paddr: 846dc7b300 cnt: 3264>                                                                                                                                      
<readmem: ffff88846dc7b300, KVADDR, "fill_thread_info", 16, (ROE|Q), 55795db094c0>                                                                                                                         
<read_proc_kcore: addr: ffff88846dc7b300 paddr: 846dc7b300 cnt: 16>                                                                                                                                        
<readmem: ffff88846dd29980, KVADDR, "fill_task_struct", 3264, (ROE|Q), 55795dbc9ee0>                                                                                                                       
<read_proc_kcore: addr: ffff88846dd29980 paddr: 846dd29980 cnt: 1664>                                                                                                                                      
<read_proc_kcore: addr: ffff88846dd2a000 paddr: 846dd2a000 cnt: 1600>                                                                                                                                      
<readmem: ffff88846dd29980, KVADDR, "fill_thread_info", 16, (ROE|Q), 55795db094c0>                                                                                                                         
<read_proc_kcore: addr: ffff88846dd29980 paddr: 846dd29980 cnt: 16>                                                                                                                                        
<readmem: ffff88846a633300, KVADDR, "fill_task_struct", 3264, (ROE|Q), 55795dbc9ee0>                                                                                                                       
<read_proc_kcore: addr: ffff88846a633300 paddr: 846a633300 cnt: 3264>                                                                                                                                      
<readmem: ffff88846a633300, KVADDR, "fill_thread_info", 16, (ROE|Q), 55795db094c0>                                                                                                                         
<read_proc_kcore: addr: ffff88846a633300 paddr: 846a633300 cnt: 16>                                                                                                                                        
  FREEBUF(1)                                                                                                                                                                                               
<readmem: ffff88846d108018, KVADDR, "task_struct.stack", 8, (FOE), 7ffd53742ee0>                                                                                                                           
<read_proc_kcore: addr: ffff88846d108018 paddr: 846d108018 cnt: 8>                                                                                                                                         
<readmem: ffffc90000014000, KVADDR, "stack magic", 8, (ROE|Q), 7ffd53742f08>                                                                                                                               
<readmem: 46d01a000, PHYSADDR, "pud page", 4096, (FOE), 55795a7f3e70>                                                                                                                                      
<read_proc_kcore: addr: 46d01a000 paddr: 46d01a000 cnt: 4096>                                                                                                                                              
crash: seek error: physical address: 46d01a000  type: "pud page"    <------------

**Comment by k-hagio** [comment]
It looks like crash-7.2.5 was released around Linux 4.20, I'm not surprised that your crash doesn't support 5.4 kernel.
What do you see with the latest crash-7.3.0?

**Comment by jpdonnell** [comment]
Hi,

You need to update your crash CLI to current level .  You can't expect crash  distributed with 4.x systems to work with new kernels.
