### ISSUE TITLE
How to configure Dump filtering ("mini dump") and use it with crash

### ISSUE THREAD

**Issue by binary-nerd** [crash-utility/crash#85]
May be this is not the right place for this question. But i believe it is strongly related to crash hence posting it here.

The below document by Hatayama san explains how to scale crash dump to systems with high memory.
https://www.fujitsu.com/jp/documents/products/software/os/linux/catalog/LinuxConJapan2013-Hatayama.pdf

We have a system with 32 Gb RAM. As a result copying `/proc/vmcore` to a disk is taking like 10 minutes.
It would be great to filter the dump like explained in the above document.
Is the dump filtering in mainline? how can we configure and use it in our systems?
Any links/references to how we can use this solution will be of great help.

Thank you.

**Comment by k-hagio** [comment]
This is the GitHub page of the makedumpfile referred in the slide deck:
https://github.com/makedumpfile/makedumpfile

If your system's architecture is supported, you can use it and crash like this:
```
# makedumpfile -l -d 31 /proc/vmcore dump.ld31
# crash vmlinux dump.ld31
```
If you use a Linux distribution, probably better to ask its community or support about how to configure.

**Comment by binary-nerd** [comment]
Thank you @k-hagio 
I am currently not using `makedumpfile`
Just doing `cp /proc/vmcore ~/kdump/vmcore`
We are having debian linux version 5.10
Hopefully i will be able to configure it.
Will try it soon.

**Comment by binary-nerd** [comment]
I am able to use `makedumpfile`
Resolving the issue now. Thank you.
