### ISSUE TITLE
crash: 16K pages not supported.

### ISSUE THREAD

**Issue by yanghuan95** [crash-utility/crash#92]
hello, my crash version is crash 7.2.8++.
I just try to open CONFIG_ARM64_16K_PAGES, and test 16KB PAGE_SIZE feature, and get a crash.
I want to use crash to trace the problem, and crash not support 16KB pages(it's true?)

**Comment by k-hagio** [comment]
Yes. It seems that the current arm64 crash does not support 16 kB pages, unfortunately.

**Comment by yanghuan95** [comment]
> Yes. It seems that the current arm64 crash does not support 16 kB pages, unfortunately.
