### ISSUE TITLE
latest crash is failing because kvbase is coming wrong (0xffffffffffffffff)

### ISSUE THREAD

**Issue by engrbansal** [crash-utility/crash#97]
Latest crash is failing because machdep->kvbase value is wrong 0xffffffffffffffff, this is happening after change https://github.com/crash-utility/crash/commit/167d37e347fe35c6f7db826e8539e192c4375564

Getting below error

crash_64: vmlinux and /var/tmp/ramdump_elf_XUtCMT do not match!
Usage:
  crash [OPTION]... NAMELIST MEMORY-IMAGE[@ADDRESS]     (dumpfile form)
  crash [OPTION]... [NAMELIST]                          (live system form)
Enter "crash_64 -h" for details.

after changing below code it is working fine

 17 diff --git a/defs.h b/defs.h
 18 index eb1c71b..d1e102a 100644
 19 --- a/defs.h
 20 +++ b/defs.h
 21 @@ -3235,7 +3235,7 @@ typedef signed int s32;
 22  #define ARM64_PAGE_OFFSET    ((0xffffffffffffffffUL) \
 23                     << (machdep->machspec->VA_BITS - 1))
 24  /* kernels >= v5.4 the kernel VA space is flipped */
 **25 -#define ARM64_FLIP_PAGE_OFFSET (-(1UL) << machdep->machspec->CONFIG_ARM64_VA_BITS)**
 **26 +#define ARM64_FLIP_PAGE_OFFSET (-(1UL) << machdep->machspec->VA_BITS_ACTUAL)**
 27  #define ARM64_FLIP_PAGE_OFFSET_ACTUAL ((0xffffffffffffffffUL) \
 28                     - ((1UL) << machdep->machspec->VA_BITS_ACTUAL) + 1)

**Comment by k-hagio** [comment]
Closing with c180a63.  Thanks.
